name: CI

on:
  push:
    branches: [ main, lya_fit_update ]
  pull_request:
    branches: [ main, lya_fit_update ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MUSE_DATA_DIR: tests/test_data
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install TANGELO with dependencies
      run: |
        pip install -e ".[dev]"
    - name: Run tests
      run: |
        pytest
